version: 0.2

phases:
  build:
    commands:
      - |
        for STACK in "monitorWeb" "ApiStack"; do
          echo "Checking stack: $STACK"
          STATUS=$(aws cloudformation describe-stacks --stack-name $STACK --query 'Stacks[0].StackStatus' --output text 2>/dev/null || echo "NOT_FOUND")
          echo "Status: $STATUS"

          if [[ "$STATUS" == "UPDATE_FAILED" || "$STATUS" == "CREATE_FAILED" || "$STATUS" == "UPDATE_ROLLBACK_FAILED" ]]; then
            echo "Rolling back $STACK..."
            aws cloudformation rollback-stack --stack-name $STACK
            aws cloudformation wait stack-rollback-complete --stack-name $STACK
            echo "$STACK rollback completed"
          else
            echo "$STACK no rollback needed"
          fi
        done