version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt -r requirements-dev.txt
      - npm install -g aws-cdk

  build:
    commands:
      - python -m pytest tests/ -v
      - cdk synth
      - cdk deploy --all

artifacts:
  files:
    - 'cdk.out/**'